# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: vendor_services_development
  pool: 5
  username: 'vendor_services'
  password: 'ronan2017'
  min_messages: WARNING
  template: template0  #template0 resolves an issue with SQL_ASCII vs UTF-8 encoding
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: vendor_services_test
  template: template0
  pool: 5
  username: 'vendor_services'
  password: 'ronan2017'
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: vendor_services_production
  pool: 5
  username: 'vendor_services'
  password:
  min_messages: WARNING
  template: template0
